<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Products.Core\Products.Core.csproj" />
    <ProjectReference Include="..\Products.Domain\Products.Domain.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
  </ItemGroup>

</Project>
