<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Folder Include="Database\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AnroveKeyManager.Core" />
    <PackageReference Include="AnroveKeyManager.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserService.Domain\UserService.Domain.csproj" />
  </ItemGroup>
</Project>
